### ISSUE TITLE
Suggestion (why not use a servo) 

### ISSUE THREAD

**Issue by Darkcast** [mhaddy/FeedGoo#2]
I been this road before and you do not want to use a server they are unreliable you can google other projects and you will see how the cat get overfed or underfed because of the unreliability of the servo. what I would suggests you use a stepper motor they are stronger and very precise 

[stepper motor reference](https://learn.adafruit.com/all-about-stepper-motors/what-is-a-stepper-motor)

**Comment by mhaddy** [comment]
Could you link me to these issues in other projects so I can review? What was their reliability issue?

While I do think a stepper motor is a good suggestion for a future release, I don't consider this to be an issue as the project uses very accurate pulse width modulation (PWM) calculations on the Pi to operate the servo. And when paired with a quality servo, the risk should be adequately mitigated. 

I think once paired with Twitter and camera support, I will have a keen detective control for over/under feeding concerns.
